### PR TITLE
Migration Refresh issue #181

### PR DESCRIPTION
**Pull request by ilamp**

### CODE REVIEW

**Comment by ohmybrew** [comment]
Thanks! Getting an error on my side that DB is unresolved. Can you add a use statement for it? It'll fix then :)

**Comment by ilamp** [comment]
I believe I already added that in the next commit. Let me double check.

**Comment by ohmybrew** [comment]
Great I'll merge in the afternoon :sunglasses:

**Comment by ilamp** [comment]
Sounds good

**Pull request merged**
