### PR TITLE
Chrome Cookies

### LINKED ISSUE #277: I am facing an issue on embedded app in iphone safari in login section
When i connect to myApp using shopify admin section, App is working but when i use login section of laravel it is showing 419 error of laravel only in apple safari. but working find in all browser chorme, firefox.

### LINKED ISSUE #367: Cookies on embedded apps blocked by Chrome 80
## Expected Behavior

Successfully authenticate embedded app on Chome 80.

## Current Behavior

Shopify store goes into a redirect loop as the cookies from the app are rejected by Chrome 80.

### Steps to Reproduce

1. [Install Chrome Beta](https://www.google.com/chrome/beta/)
2. Launch the app within the Shopify store
3. The app would not authenticate successfully.

### Context

Come February 2020, Chrome 80 will be released and will begin rejecting cookies from a third party site that is not set to `SameSite=None; Secure`. (Ref: [Chromium blog](https://blog.chromium.org/2019/10/developers-get-ready-for-new.html)) According to Google, Mozilla and Microsoft will be making the same changes in future versions of their browser.

As embedded apps on Shopify are considered third-party, if the app's cookie is not set to `SameSite=None; Secure`, the behaviour described above would occur. To further complexify things, Safari on macOS 10.14 and iOS 12 (and [some others](https://www.chromium.org/updates/same-site/incompatible-clients)) would behave incorrectly when a cookie with `SameSite=None; Secure` is submitted. As such, the app needs to not send that flag to some of these browsers. In other words, simply setting the cookies config in Laravel would not be sufficient.

While this is a Laravel thing more than an issue with this package (Laravel supports setting these flags on cookies via `session.php`), all projects that use this package to develop embedded apps on Shopify would encounter this issue. So perhaps it could be something this package could handle?

Thought to bring this up as a topic of discussion. I'm open to contribute code to this but would love to hear your thoughts first, especially from @ohmybrew. 

**Additional Reference:** [Shopify article about this issue](https://help.shopify.com/en/api/guides/samesite-cookies)

### PR DESCRIPTION
**Pull request by darrynten**
From ~~4th of Feb~~ 17th of Feb Shopify Apps must all send SameSite=none cookies with the secure flag set.

This is because Chrome 80+ has this as a hard requirement in order for embedded apps to continue to work.

This PR is based on the initial work performed by @jedimdan in PR #375 

The key difference here is that the check has been moved to the ShopSession Service level, instead of being on the Middleware level, and the tests are performed on actual requests, not just the check method.

Additionally, all derived Shopify Host addresses will be https instead of http (this is a hard requirement for secure cookies to work).

This patch makes the need to edit the `config/sessions.php` file in the host application redundant. Changing those values can be harmful as it would set those flags for incompatible browsers and result in broken apps for those users.

Resolves #367 
~~#277~~ (See comment from @jedimdan for why this is not actually resolved)

## References

[Shopify Announcement](https://help.shopify.com/en/api/guides/samesite-cookies)
[Known Incompatible Clients](https://www.chromium.org/updates/same-site/incompatible-clients)

### CODE REVIEW

**Comment by jedimdan** [comment]
Thanks @darrynten, this is much better than what I had. Will close my PR.

By the way, I don't think #277 is related to the Google Chrome cookie issue so I don't think this PR should be set to resolve that. #277 targets Safari ITP 2.0 (Ref: https://help.shopify.com/en/api/guides/itp-impact). The discussion just got driven to the Chrome cookie issue as at that point it seemed like they were related. But now we know clearly it's 2 separate issues.

**Comment by darrynten** [comment]
@jedimdan I see now that #277 isn't actually related, thanks for pointing that out.

I'm sure we can do something similar like we did in this PR to tackle that problem.

Waiting on @ohmybrew for approval!

**Comment by jedimdan** [comment]
@darrynten the only blocker would be the structural changes that @ohmybrew is doing to the package as a whole as mentioned in his note on the readme. 

@ohmybrew is there anything we can do to make it easier for this PR (or future PRs for that matter) work with what you're [working on now](https://github.com/ohmybrew/laravel-shopify/tree/structure-change)?

**Comment by ohmybrew** [comment]
Hi, currently no. It's a complete change to the entire package, many parts are rewritten.The PR if you've issued one it can remain, and once I'm done my changes and new testing, I'll see how to pull it in, most likely manually.On Jan. 31, 2020 09:14, Daniel Tsou <notifications@github.com> wrote:@darrynten the only blocker would be the structural changes that @ohmybrew is doing to the package as a whole as mentioned in his note on the readme.
@ohmybrew is there anything we can do to make it easier for this PR (or future PRs for that matter) work with what you're working on now?

**Comment by darrynten** [comment]
@ohmybrew the main concern here is that the deadline for the Chrome cookie change is looming - 4 days and counting before all our apps go offline.

**Comment by ohmybrew** [comment]
I'm aware of that yeah. Unfortunately I'm only one person. I can merge this in and push a release Sunday possibly but there's still other issues browsers are introducing.. the release would solve what your PR is pushing but I can't focus on everything.This package is unfortunately is starting to become a burden to work on. The rewrite in the other branch once done will make things much easier to maintain but I'm constantly getting dozens of emails weekly from people who've never used Laravel, asking for help because they don't know how to install the package, people emailing me complaining some issue in queue is still not fixed, people generally emailing asking if it's dead (which it's clearly not if someone clicked the commit tab).I support what I can, freely, out of my free time between a full time job, family life, and personal stuff. That itself is a challenge to overcome.I'm aware of the cookie issue and deadline but there's also the other stuff like ITP for Safari that's not even touched yet.. the changes browsers are doing is quite annoying as it's forcing frontend and backend bouncing around through the iframe to solve issues with cookies. There's just so much I can do.I'll attempt a release with your patch Sunday though if it's something that'll help people though! It'll probably be the last release I can support from the master branch though as I really want to focus on the new branch, which is about 95% done, just needs a rewrite on unit tests and physical tests ;)Keep an eye out for Sunday night for the release.On Jan. 31, 2020 10:10, Darryn Ten <notifications@github.com> wrote:@ohmybrew the main concern here is that the deadline for the Chrome cookie change is looming - 4 days and counting before all our apps go offline.

**Comment by ohmybrew** [comment]
But also, I'm grateful for PRs like this, I've been very impressed with people like yourself diving in a helping with issues the past couple years! it definitely helps take some strain off.On Jan. 31, 2020 10:10, Darryn Ten <notifications@github.com> wrote:@ohmybrew the main concern here is that the deadline for the Chrome cookie change is looming - 4 days and counting before all our apps go offline.

**Comment by jedimdan** [comment]
@ohmybrew we are all so grateful for the work that you’ve put in that saved so many of us thousands of hours of work. As a community, we are as responsible for the success and the longevity of this package. Ideally we would want to find ways to support you so that you can focus doing what only you can do (such as making a release etc), and the rest of us can step in for the more trivial stuff that are just bogging you down. 

Since we are all so reliant on your package, I’m sure many of us would be willing to volunteer to tackle some of these browser issues too so you can focus on the bigger problems. I think I speak for many of us that this burden shouldn’t be solely on you.

**Comment by ohmybrew** [comment]
Thank you. I don't think it's all on me, certain parts are but the past couple years, people like yourself stepping in and handling a PR, or commenting on an issue to assist someone, contributing code has been a great help already.Time is just the sad factor in everything, like any project. If I had full days to commit to the new branch for example, as opposed to a few hours a night here and there, it would be the world of difference.. so sadly it's just time crunch for many thing.My goal is to improve the package which is why I undertook reorganization and rewriting it the past month. It's definately much more easier to work with now. Code is separated into isolated bits, there's utilization of the IoC and injection now, there's a swap to use the user model now and not it's own shop model so people can make their own auth guards, centralized API handler, as well as many other improvements :)On Jan. 31, 2020 12:46, Daniel Tsou <notifications@github.com> wrote:@ohmybrew we are all so grateful for the work that you’ve put in that saved so many of us thousands of hours of work. As a community, we are as responsible for the success and the longevity of this package. Ideally we would want to find ways to support you so that you can focus doing what only you can do (such as making a release etc), and the rest of us can step in for the more trivial stuff that are just bogging you down.

Since we are all so reliant on your package, I’m sure many of us would be willing to volunteer to tackle some of these browser issues too so you can focus on the bigger problems. I think I speak for many of us that this burden shouldn’t be solely on you.

**Comment by darrynten** [comment]
@ohmybrew thanks so much for the update.

I am planning on jumping onto the ITP issues for Safari as soon as possible.

I will wait for a new release tomorrow, and if it has not been released by Monday I will update all of our apps to work off of my forks working branch until there is a resolution.

Regarding time on your side - I'm open to assisting on a maintainer level. Feel free to reach out to me if this would help you get a handle on things.

**Comment by darrynten** [comment]
Just received an announcement that Google have delayed the change until the 17th of Feb

😌

**Comment by amosmos** [comment]
Came here to read about the fix to the Chrome Cookies issue, but read the discussion and just wanted to jump in and say a huge thanks to @ohmybrew! You did and doing an amazing work and we all appreciate it and want to help as much as we can!

Thanks,
Amos

**Comment by amosmos** [comment]
@darrynten and @jedimdan, you seem to be totally experts on this subject so I have a quick question for you, if that's alright.

My app is using Shopify Laravel v6. I wonder if it would make sense for me to go through the upgrade process from v6 to v10 just for this issue, or is there a quicker (even if "dirtier") solution just to get through the Chrome change date.

What do you think?

Thanks!
Amos

**Comment by tzookb** [comment]
hey @darrynten 

where did you get the delay of chrome release?

I was happy you mentioned that, but on this site it still says the 4th of February
https://www.chromestatus.com/features/schedule


Thanks!

**Comment by jedimdan** [comment]
@amosmos I think @darrynten knows the ins and outs of this package a lot better so he can probably give you a better answer. 

But from my personal experience, apart from updating the config file, I don't recall having had to do many changes to my app with each release (I think I started at v7). Best way to know is to read the release notes from v6 onwards, and maybe take a peek at the [difference](https://github.com/ohmybrew/laravel-shopify/compare/v6.0.0...v10.3.0) too.

**Comment by jedimdan** [comment]
@tzookb [The launch timeline on this page last updated on the 30th of Jan shows Feb 17](https://www.chromium.org/updates/same-site)

**Comment by amosmos** [comment]
Thanks so much for the quick answer @jedimdan!

I got the impression upgrading from V6 to V10 might be complex because I see the file and folder is very different. And also everything seems to be working ok for now, so I thought I'd just wait to redo the app with new Laravel and the new version of this package one day.

For now, what thought I had is to use your original idea of the middleware. Other than it being better dealt in the service level by this package (which I of course agree with), do you think there's any reason not to do it?

Would also wait to hear @darrynten thoughts like you suggested.

Thanks,
Amos

**Comment by Kyon147** [comment]
Would your best bet just be setting up a dev environment, update the package and work through any errors?

When you are done you can just push the changes to master. Rewriting would be absolute best but there is a cost impact on that for any business/app. We usually for major release updates, have a dev branch which you can use and break and improve until you want to go live with it.

It is one of the main reasons for having GIT after all with CI/CD

**Comment by nonghinh** [comment]
I tried to fix Samesite issue by this way:
1. Go to vendor/symfony/http-foundation/Cookie.php
2. Find const SAMESITE_NONE = 'none';
image
if it not exists, run "composer update" to update symfony Or:
+ add const SAMESITE_NONE = 'none'; ( line no 33)
+ around line 132 add SAMESITE_NONE to the array
image

== Then config in /config/session.php
image

=====
I tried installing My app with ngrok And has error 419 in /authenticate
I tried installing My app on real server, it worked
========
Anyone try it?

**Comment by muhammadasfar** [comment]
Anyone can write steps to apply this new version on the existing app?

Just updated package from dev-master to v10.3.0. But did not see any change in the browser console of [beta chrome 80 beta](https://www.google.com/chrome/beta/) as in the below screenshot.

image

**Laravel Framework 5.8.36
Valet Linux**

secondly, I have also applied @jedimdan [gist](https://gist.github.com/jedimdan/e6c78a2665f788eda9a3e3f3b4e1f982) that works fine and apply changes of samesite=none, secure

**Comment by jedimdan** [comment]
@muhammadasfar just to confirm that you no longer have my middleware in your code, right?

**Comment by muhammadasfar** [comment]
@jedimdan Yes, I don't have any **middleware** in my app code and regarding samesite=none. what I did is
just updated package version from dev-master to v.10.3.0 using composer and check changes in my application on chrome 80 beta.

**Comment by jedimdan** [comment]
@muhammadasfar if running `composer info ohmybrew/laravel-shopify` confirms that you have `v10.3.0` installed, then can you also try manually going to your `session.php` and changing `secure` to `true` and `same_site` to `none` to see if your app is even capable of sending the correct flags for the cookies. If even that doesn't work, then it might not have to do with this package. There might be something else preventing the cookies from being set correctly. 

You might also want to consider updating all your composer packages with `composer update`.

**Comment by muhammadasfar** [comment]
Already updated composer packages with `composer update`

**Command** executed  `composer info ohmybrew/laravel-shopify`
**Result**:
image

After changing manually in `session.php`
`secure` to `true` and `same_site` to `none`
**Result:**
image

But when I reverted `session.php` values to default then the package is not changing anything in the console.

If anyone is not experiencing this behaviour then I think there is an issue in my app.

**Comment by jedimdan** [comment]
@muhammadasfar yea I just tried it on mine and it seems to be working fine for me.

**Comment by amosmos** [comment]
@jedimdan  - Hi - is there any reason you see that I should not add your original middleware instead of updating the package?

Thanks!

**Comment by muhammadasfar** [comment]
@jedimdan and @darrynten I think there is a issue in these two functions at line number 295, 296 of file src/ShopifyApp/Services/ShopSession.php

`$browser = $this->getBrowserDetails();`
`$platform = $this->getPlatformDetails();`

In my case `getPlatformDetails()` function returns `Error Undefined offset: 1` so that's why `checkSameSiteNoneCompatible()` is always returning false because this function is in **try** and it is not adding samesite=none, secure=true in the browser console.

I am using 
**Laravel Framework 5.8.36
Ohmybrew/laravel-shopify: 10.3.0
PHP 7.2.27
Server: Nginx
Valet Linux**

**Comment by jedimdan** [comment]
@muhammadasfar hmm you might have found something. Could you share with us the user agent that your app is receiving? can you try to `dd(request()->header('user-agent')` somewhere?

**Comment by mferrario** [comment]
@muhammadasfar @jedimdan I also see this error. I did a manual patch a few days ago (before the update) and uploaded to AWS beanstalk and have been getting notifications of the same  exceptions. See Below.

For debugging, I capture the domain name that triggers the exception and noticed that for this error, it appears to be from robots crawling the site. AWS does health checks that also cause this error. In the image attached, "example.com" is the weird domain that caused this exception. 

So, I suspect it is robots crawling the site who do not have a minor version??? not sure... but I think this is where it might be breaking:  `('minor' => $pieces[1],)`. That said, checkSameSiteNoneCompatible() only uses $browser['major'], so is there value in capturing browser minor and float? I haven't tried to comment out those two fields to see if I am still seeing the error. Might try tonight or later tomorrow and will report back. 

**Errors I am seeing:** 

`at HandleExceptions->handleError(8, 'Undefined offset: 1', '/var/app/current/vendor/ohmybrew/laravel-shopify/src/ShopifyApp/Services/ShopSession.php', 336, array('version' => false, 'pieces' => array('')))
in ShopSession.php line 336`

exception

**Comment by jedimdan** [comment]
@mferrario Could you also share the user agent that's causing it? It'll help us in producing a fix.

**Comment by yukari1414** [comment]
> I tried to fix Samesite issue by this way:
> 
> 1. Go to vendor/symfony/http-foundation/Cookie.php
> 2. Find const SAMESITE_NONE = 'none';
>    image
>    if it not exists, run "composer update" to update symfony Or:
> 
> * add const SAMESITE_NONE = 'none'; ( line no 33)
> * around line 132 add SAMESITE_NONE to the array
>   image
> 
> == Then config in /config/session.php
> image
> 
> # =====
> I tried installing My app with ngrok And has error 419 in /authenticate
> I tried installing My app on real server, it worked
> Anyone try it?

It's never a good idea to modify vendor files. Here's the [commit](https://github.com/symfony/http-foundation/commit/f9bb07318c806a7dbe246f196b8af941585ad8e7) in [symfony/http-foundation](https://github.com/symfony/http-foundation) that actually adds support for `SameSite=None`.

You can find the closest version to upgrade to for minimal risks at the section that lists all the versions that has this commit.
Screenshot 2020-02-05 at 15 55 19

**Comment by JDSHINDE** [comment]
> I tried to fix Samesite issue by this way:
> 
> 1. Go to vendor/symfony/http-foundation/Cookie.php
> 2. Find const SAMESITE_NONE = 'none';
>    image
>    if it not exists, run "composer update" to update symfony Or:
> 
> * add const SAMESITE_NONE = 'none'; ( line no 33)
> * around line 132 add SAMESITE_NONE to the array
>   image
> 
> == Then config in /config/session.php
> image
> 
> # =====
> I tried installing My app with ngrok And has error 419 in /authenticate
> I tried installing My app on real server, it worked
> Anyone try it?

Use firefox when you work on ngrok, try to install again with this browser.

**Comment by amosmos** [comment]
Hi @jedimdan  - Do you see any problem with adding your code to a middleware as your original suggestion? I mean as a quick and easy fix for now?

**Comment by jedimdan** [comment]
@amosmos I personally don't, but I might be wrong. Best to test it out. Good news is that Google has made it easy to test. You can read about how to enable the flags needed in Chrome 80 in this comment https://github.com/ohmybrew/laravel-shopify/issues/367#issuecomment-584974065

**Pull request merged**
