### PR TITLE
Middleware that sets cookies to samesite=none

### LINKED ISSUE #367: Cookies on embedded apps blocked by Chrome 80
## Expected Behavior

Successfully authenticate embedded app on Chome 80.

## Current Behavior

Shopify store goes into a redirect loop as the cookies from the app are rejected by Chrome 80.

### Steps to Reproduce

1. [Install Chrome Beta](https://www.google.com/chrome/beta/)
2. Launch the app within the Shopify store
3. The app would not authenticate successfully.

### Context

Come February 2020, Chrome 80 will be released and will begin rejecting cookies from a third party site that is not set to `SameSite=None; Secure`. (Ref: [Chromium blog](https://blog.chromium.org/2019/10/developers-get-ready-for-new.html)) According to Google, Mozilla and Microsoft will be making the same changes in future versions of their browser.

As embedded apps on Shopify are considered third-party, if the app's cookie is not set to `SameSite=None; Secure`, the behaviour described above would occur. To further complexify things, Safari on macOS 10.14 and iOS 12 (and [some others](https://www.chromium.org/updates/same-site/incompatible-clients)) would behave incorrectly when a cookie with `SameSite=None; Secure` is submitted. As such, the app needs to not send that flag to some of these browsers. In other words, simply setting the cookies config in Laravel would not be sufficient.

While this is a Laravel thing more than an issue with this package (Laravel supports setting these flags on cookies via `session.php`), all projects that use this package to develop embedded apps on Shopify would encounter this issue. So perhaps it could be something this package could handle?

Thought to bring this up as a topic of discussion. I'm open to contribute code to this but would love to hear your thoughts first, especially from @ohmybrew. 

**Additional Reference:** [Shopify article about this issue](https://help.shopify.com/en/api/guides/samesite-cookies)

### PR DESCRIPTION
**Pull request by jedimdan**
Attempt to fix #367.

What I'm not sure is the strategy to insert this middleware. Should this be included in the install docs for developers to include into the global middleware list? The consideration is that this only applies for requests that are within an embedded app.

Also, the other part I'm not sure is if you are okay with a new dependency, seeing that this library has been very clean from other dependencies so far.

**Based on Shopify's implementation:** https://github.com/Shopify/shopify_app/pull/851

### CODE REVIEW

**Comment by jedimdan** [comment]
@darrynten I've got this working middleware that I already use in my production. I just need help figuring out what's the most appropriate way to make it available in this package. Do you have any suggestions?

**Comment by darrynten** [comment]
I've been looking at this and there is no need to add any code to fix this issue.

The change you mentioned in #277 works perfectly.

For others who may need this info, the change needs to be done in the host laravel app that is using this.

You make the following changes in `config/session.php`

Change:

```
    'secure' => env('SESSION_SECURE_COOKIE', false),
```

to

```
    'secure' => env('SESSION_SECURE_COOKIE', true),
```

Change:

```
    'same_site' => null,
```

to

```
    'same_site' => 'none',
```

After that's done then the expected policies are in place and Shopify is happy with the update.

This means that the changes proposed in this PR are redundant, and I would vote to close the PR without merging.

**Comment by jedimdan** [comment]
Hi @darrynten the additional changes are necessary because of the browser compatibility issues. It's not sufficient to simply change the cookie settings. 

I've explained this in detail in #367. The challenge is that the browsers that have issues are quite recent (iOS 12 and macOS 10.14) so it's quite critical that the compatibility issues are covered. This code is based on Shopify's changes to their own Rails library as well.

**Comment by jedimdan** [comment]
Regarding compatibility issues please read [this article](https://www.chromium.org/updates/same-site/incompatible-clients). This cookie completely breaks the app on Safari for iOS 12 and macOS 10.14 so it needs to not change in those browsers.

**Comment by darrynten** [comment]
I'm actively working on this, I will update as soon as possible

**Comment by jedimdan** [comment]
> I'm actively working on this, I will update as soon as possible

What's your game plan?

**Comment by jedimdan** [comment]
@darrynten I also recommend editing your recommendation above on changing the sessions config as doing so will cause the app to unexpectedly break on Safari for macOS 10.14, which I believe is still heavily used.

**Comment by darrynten** [comment]
Please see #382 it resolves the problem cleanly on the Service level instead of on the Middleware level

**Comment by jedimdan** [comment]
Closing this PR in favour of #382

**Pull request closed without merging**
